### ISSUE TITLE
Is hrs package used for ECG or PPG signal?

### ISSUE THREAD

**Issue by Yuyang01** [rhenanbartels/hrv#18]
I am process the PPG signal but I got error:
1. This is the code I am implementing
```python 

from hrv.classical import frequency_domain
from hrv.io import read_from_text
ppg = np.loadtxt('ecg.txt', delimiter=',')
results = frequency_domain(
    rri=ppg,
    fs=64.0,
    method='welch',
    interp_method='cubic',
    detrend='linear'
)
print(results)
```

2. The error:
```python
Traceback (most recent call last):

  File "/Users/yuyang01/Documents/publication/journal/workloadVR/python/hrv.py", line 51, in <module>
    detrend='linear'

  File "/Users/yuyang01/miniconda3/envs/py37/lib/python3.7/site-packages/hrv/classical.py", line 188, in frequency_domain
    rri = _interpolate_rri(rri, time, fs, interp_method)

  File "/Users/yuyang01/miniconda3/envs/py37/lib/python3.7/site-packages/hrv/utils.py", line 77, in _interpolate_rri
    return _interp_cubic_spline(rri, time, fs)

  File "/Users/yuyang01/miniconda3/envs/py37/lib/python3.7/site-packages/hrv/utils.py", line 83, in _interp_cubic_spline
    time_rri_interp = _create_interp_time(time, fs)

  File "/Users/yuyang01/miniconda3/envs/py37/lib/python3.7/site-packages/hrv/utils.py", line 97, in _create_interp_time
    return np.arange(0, time[-1] + time_resolution, time_resolution)

TypeError: 'NoneType' object is not subscriptable
```

3. Here is the data: 
[ppg.txt](https://github.com/rhenanbartels/hrv/files/4348482/ppg.txt)

Best regards,

**Comment by rhenanbartels** [comment]
Hi @Yuyang01, how are you doing? 

The `hrv` expects that you already have the R peaks detected and you already have the RRi series.

Based on the signal you've attached in the issue, you can detect the R peaks doing the following:

```python
import numpy as np
from biosppy.signals import ecg

signal = np.loadtxt('ppg.txt')

# you need to provide fs = the frequency in which the ECG was recorded
out = ecg.ecg(signal=signal, sampling_rate=fs, show=True)

rri = np.diff(biosppy_ecg["rpeaks"]) / fs
```

**Comment by Yuyang01** [comment]
Thank you. I will give it a try:)
